apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: fjqggzn5b-python 
  janus-idp.io/tekton: fjqggzn5b-python
  backstage.io/kubernetes-id: fjqggzn5b-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fjqggzn5b-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml